xA_path = "./data/02_model_input/mineops_cd_xA.npy"
xB_path = "./data/02_model_input/mineops_cd_xB.npy"
y_path = "./data/02_model_input/mineops_cd_y.npy"
output_dir = "./output"
model_config_path = "./configs/model_config_01.toml"