name = "SnuNet_Model_64"
in_channels = 6
num_classes = 1
threshold = 0.5
base_channel = 16
depth = 2
pretrained_dir = ""
img_size = 512
batch_size = 2
eval_every = 50
num_steps = 100
warmup_steps = 35
gradient_accumulation_steps = 1
max_grad_norm = 1
learning_rate = 1e-3
weight_decay = 1e-8
seed = 42
